      SUBROUTINE MYSCHAN2(P1,MTOP,MW,ANS)
C  
C Generated by MadGraph II Version 3.0. Updated 02/19/04                
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : d u~ -> e- ve~ b~ b  
C  
C Crossing   1 is d u~ -> e- ve~ b~ b  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (NCOMB=  64, NCROSS=  1)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,6),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(6,NCOMB),NTRY
      REAL*8 T, P(0:3,6), MTOP, MW
      REAL*8 MMYSCHAN2
      INTEGER IHEL,IDEN(NCROSS),IC(6,NCROSS)
      INTEGER IPROC, I
      LOGICAL GOODHEL(NCOMB,NCROSS)
C  
C GLOBAL VARIABLES
C  

      DATA (NHEL(IHEL,   1),IHEL=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,   3),IHEL=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,   4),IHEL=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,   5),IHEL=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,   6),IHEL=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,   9),IHEL=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  10),IHEL=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  11),IHEL=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  12),IHEL=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  15),IHEL=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  16),IHEL=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  17),IHEL=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  18),IHEL=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  19),IHEL=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  20),IHEL=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  21),IHEL=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  22),IHEL=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  23),IHEL=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  24),IHEL=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  25),IHEL=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  26),IHEL=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  27),IHEL=1,6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  28),IHEL=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  29),IHEL=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  30),IHEL=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  31),IHEL=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  32),IHEL=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  33),IHEL=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  34),IHEL=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  35),IHEL=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  36),IHEL=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  37),IHEL=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  38),IHEL=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  39),IHEL=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  40),IHEL=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  41),IHEL=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  42),IHEL=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  43),IHEL=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  44),IHEL=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  45),IHEL=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  46),IHEL=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  47),IHEL=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  48),IHEL=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  49),IHEL=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  50),IHEL=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  51),IHEL=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  52),IHEL=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  53),IHEL=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  54),IHEL=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  55),IHEL=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  56),IHEL=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  57),IHEL=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  58),IHEL=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  59),IHEL=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  60),IHEL=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  61),IHEL=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  62),IHEL=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  63),IHEL=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  64),IHEL=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (  IC(IHEL,  1),IHEL=1,6) / 1, 2, 3, 4, 5, 6/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
      
C      PRINT *," 1 P1(E,px,py,pz) ",P1(0,1),P1(1,1),P1(2,1),P1(3,1)
C      PRINT *," 1 P2(E,px,py,pz) ",P1(0,2),P1(1,2),P1(2,2),P1(3,2)
C      PRINT *," 1 P3(E,px,py,pz) ",P1(0,3),P1(1,3),P1(2,3),P1(3,3)
C      PRINT *," 1 P4(E,px,py,pz) ",P1(0,4),P1(1,4),P1(2,4),P1(3,4)
C      PRINT *," 1 P5(E,px,py,pz) ",P1(0,5),P1(1,5),P1(2,5),P1(3,5)
C      PRINT *," 1 P6(E,px,py,pz) ",P1(0,6),P1(1,6),P1(2,6),P1(3,6)
      
      
      ANS(1) = 0D0
C      PRINT *, "ANS(1): ", ANS(1)
      DO IHEL=1,NCOMB
        T=MMYSCHAN2(P1 ,MTOP,MW,NHEL(1,IHEL))		
C        IF (T .GT. 0) THEN 
C	  PRINT *,"IHEL, T ", IHEL,T
C	ENDIF
C      PRINT *, "B ANS(1): ", ANS(1)
        ANS(1)=ANS(1)+T
C      PRINT *, "C ANS(1): ", ANS(1)
      ENDDO
      
C      PRINT *, "D ANS(1): ", ANS(1)
      ANS(1)=ANS(1)/DBLE(IDEN(1))
C      PRINT *," ME2 for MTOP",ANS(1), MTOP
      END

      REAL*8 FUNCTION MMYSCHAN2(P,MTOP,MW,NHEL)
C  
C Generated by MadGraph II Version 3.0. Updated 02/19/04                
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,4)
C  
C FOR PROCESS : u d~ -> e+ ve b b~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      double precision  Pi, Fourpi, Rt2, gfermi
      parameter( Pi = 3.14159265358979323846d0 )
      parameter( Fourpi = 4.0d0  * Pi )
      parameter( Rt2   = 1.414213562d0 )
      parameter( gfermi = 1.16639d-5 )
C
C ARGUMENTS 
C  
      REAL*8 P(0:3,6),MTOP,MW
      INTEGER NHEL(6)
C  
C LOCAL VARIABLES 
C  
      COMPLEX*16 AMP(1),JAMP(1)
      COMPLEX*16 W(6,9)
      double precision  sin2w,sw,alpha,ee,gw
      double precision  tmass,wmass,bmass,wwidth,twidth
      double complex gwf(2)   
C      tmass   = 174.3d0  !top pole mass
      tmass   = MTOP  !top pole mass
      wmass   = MW !W  pole mass mw=80.419d0
      bmass   = 4.7d0    !bottom pole mass
      wwidth  = 2.04759d0   
      sin2w=0.23120 
      sw  = sqrt( sin2w )
C      alpha = 1/128.9000    
      alpha  = Rt2*gfermi*wmass**2*sin2w/pi      
C      PRINT *, "alpha: ", alpha, Rt2, gfermi, wmass, sin2w
      ee  = sqrt( alpha * Fourpi ) 
      gw   = ee/sw
C      Two = 2.0d0 

C     all this is set in setpara.f usually	                                            
      gwf(1) = dcmplx( -ee/sqrt(2.0d0*sin2w), Zero )
C      PRINT *, "ee: " , ee, "denom: " , sqrt(2.0d0*sin2w), "gwf(1): ",
C& gwf(1)
      gwf(2) = dcmplx(  Zero              , Zero )
C      twidth  = 1.6d0 
      call mytopwidth(tmass,wmass,wwidth,twidth)
C      call topwid(tmass,wmass,bmass,wwidth,gw,twidth)
C      PRINT *," tmass, twidth ",tmass,twidth

C ----------
C BEGIN CODE
C ----------
C       PRINT *," P1(E,px,py,pz) ",P(0,1),P(1,1),P(2,1),P(3,1)
C       PRINT *," P2(E,px,py,pz) ",P(0,2),P(1,2),P(2,2),P(3,2)
C       PRINT *," P3(E,px,py,pz) ",P(0,3),P(1,3),P(2,3),P(3,3)
C       PRINT *," P4(E,px,py,pz) ",P(0,4),P(1,4),P(2,4),P(3,4)
C       PRINT *," P5(E,px,py,pz) ",P(0,5),P(1,5),P(2,5),P(3,5)
C       PRINT *," P6(E,px,py,pz) ",P(0,6),P(1,6),P(2,6),P(3,6)
 
C      PRINT *, "AMP: ", AMP(1)
      CALL IXXXXX(P(0,1   ),ZERO ,NHEL(1   ),+1,W(1,1	))	  
      CALL OXXXXX(P(0,2   ),ZERO ,NHEL(2   ),-1,W(1,2	))	  
      CALL OXXXXX(P(0,3   ),ZERO ,NHEL(3   ),+1,W(1,3	))	  
      CALL IXXXXX(P(0,4   ),ZERO ,NHEL(4   ),-1,W(1,4	))	  
      CALL IXXXXX(P(0,5   ),BMASS ,NHEL(5   ),-1,W(1,5   ))	  
      CALL OXXXXX(P(0,6   ),BMASS ,NHEL(6   ),+1,W(1,6   ))	  
C      PRINT *, "JIOXXX: ", W(1,1), W(1,2), GWF, WMASS, WWIDTH
      CALL JIOXXX(W(1,1   ),W(1,2   ),GWF ,WMASS   ,WWIDTH  ,W(1,7   ))    
      CALL JIOXXX(W(1,4   ),W(1,3   ),GWF ,WMASS   ,WWIDTH  ,W(1,8   ))    
      CALL FVIXXX(W(1,5   ),W(1,8   ),GWF ,TMASS   ,TWIDTH  ,W(1,9   ))    
C      PRINT *, "W(1, {1, 2, 3, 4, 5, 6, 7, 8, 9})", W(1,1), W(1, 2),
C&  W(1, 3), W(1, 4), W(1, 5), W(1, 6), W(1, 7), W(1, 8), W(1, 9)
      CALL IOVXXX(W(1,9   ),W(1,6   ),W(1,7   ),GWF ,AMP(1   ))            
      JAMP(   1) = -AMP(   1)
C      PRINT *, "JAMP: ", JAMP(1)
      MMYSCHAN2 = JAMP(1)*DCONJG(JAMP(1))*9.0d0

      END


